# Generated by Django 4.2.10 on 2024-03-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.FileField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
