# Generated by Django 4.2.10 on 2024-04-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="img",
            field=models.FileField(default="default.png", upload_to="profile_pics"),
        ),
    ]
