# Generated by Django 4.2.10 on 2024-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_customuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.FileField(default='/v1/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
