# Generated by Django 4.2.10 on 2024-04-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authapp", "0002_alter_customuser_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceprovider",
            name="avg_cost",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="img",
            field=models.FileField(
                default="/v1/profile_pics/default.png", upload_to="profile_pics"
            ),
        ),
    ]
