# Generated by Django 4.2.10 on 2024-03-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0003_alter_customuser_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=1000)),
                ('request_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.customer')),
                ('service_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.serviceprovider')),
            ],
        ),
    ]
