# Generated by Django 4.2.10 on 2024-03-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_provider',
        ),
    ]
