# Generated by Django 4.2.10 on 2024-03-09 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_alter_customer_address'),
        ('service', '0002_remove_servicerequest_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.customer'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authapp.serviceprovider'),
        ),
    ]
